apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-generation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-generation
  template:
    metadata:
      labels:
        app: video-generation
    spec:
      containers:
        - name: video-generation
          image: $REGION_OCIR/$TENANCY_NAME/generative-api/video-generation:0.0.1
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              memory: 9000Mi
            limits:
              nvidia.com/gpu: 1
          imagePullPolicy: Always
      imagePullSecrets:
              - name: ocirsecret
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoExecute"

---
apiVersion: v1
kind: Service
metadata:
  name: video-generation
spec:
  selector:
    app: video-generation
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP