# image-generation

apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-generation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-generation
  template:
    metadata:
      labels:
        app: image-generation
    spec:
      containers:
        - name: image-generation
          image: $REGION_OCIR/$TENANCY_NAME/generative-api/image-generation:0.0.1
          env:
            - name: discovery.type
              value: single-node
            - name: HUGGINGFACEHUB_MODEL
              value: "stabilityai/stable-diffusion-2-1-base"
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              memory: 6000Mi
            limits:
              nvidia.com/gpu: 1
          imagePullPolicy: Always
      imagePullSecrets:
        - name: ocirsecret
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoExecute"
---
apiVersion: v1
kind: Service
metadata:
  name: image-generation
spec:
  selector:
    app: image-generation
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3001
  type: ClusterIP